parameters:
  ageYoungQuery:
    name:                                    ageyoung
    in:                                      query
    description:                             >-
          Youngest age that intercepts with the dataset (in calibrated years
          before present, with 0 at 1950CE)
    required:                                false
    schema:
      type:                                  integer
      format:                                int64
      example:                               -60
      maximum: 23900000
      minimum: -100
  ageOldQuery:
    name:                                    ageold
    in:                                      query
    description:                             >-
          Oldest age that intercepts with the dataset (in calibrated years
          before present, with 0 at 1950CE)
    required:                                false
    schema:
      type:                                  integer
      format:                                int64
      example:                               11430
      maximum: 23900000
      minimum: -100
  ageOfQuery:
    name:                                    ageof
    in:                                      query
    description:                             >-
          Dataset age ranges must contain this age (in calibrated years before
          present, with 0 at 1950CE)
    required:                                false
    schema:
      type:                                  integer
      format:                                int64
      example:                               6700
      maximum: 23900000
      minimum: -100
  altMinQuery:
    name:                                    altmin
    description:                             Minimum altitude of the dataset site location (in meters)
    in:                                      query
    required:                                false
    schema:
      type:                                  integer
      format:                                int64
      minimum:  -500
      maximum: 8900
      example:                               200
  altMaxQuery:
    name:                                    altmax
    in:                                      query
    description:                             Maximum altitude of the dataset site location (in meters)
    required:                                false
    schema:
      type:                                  integer
      format:                                int64
      minimum:  -500
      maximum: 8900
      example:                               300
  contactidQuery:
    name:                                    contactid
    description:                             >-
          Unique contact identifier within the Neotoma Database, alone or
          comma separated.
    in:                                      query
    required:                                false
    schema:
      type:                                  integer
      format:                              int64
      minimum:                             1
      example:                             44
  contactidPath:
    name:                                    contactid
    description:                             >-
          Unique contact identifier within the Neotoma Database, alone or
          comma separated.
    in:                                      path
    required:                                true
    schema:
      type:                                  integer
      format:                              int64
      minimum:                             1
      example:                             44
  contactNameQuery:
    name:                                    contactname
    description:                             Last name of the researcher (may use the % wildcard)
    in:                                      query
    required:                                false
    schema:
      type:                                  string
      example:                               Grimm, Eric Christopher
  contactStatusQuery:
    name:                                    contactstatus
    in:                                      query
    description:                             Current employment status
    required:                                false
    schema:
      type:                                  string
      enum:
        - active
        - deceased
        - defunct
        - extant
        - inactive
        - retired
        - unknown
      example:                               active
  datasetidQuery:
    name:                                    datasetid
    description:                             Valid Neotoma dataset identifier (integer), either singly or in a comma separated list.
    in:                                      query
    required:                                false
    schema:
      type:                                  integer
      format:                                int32
      minimum:                               0
  datasetidPath:
    name:                                    datasetid
    description:                             Valid Neotoma dataset identifier (integer), either singly or in a comma separated list.
    in:                                      path
    required:                                true
    schema:
      type:                                  integer
      format:                                int32
      minimum:                               0
      example:          100
  datasettypeQuery:
    name:                                datasettype
    description:                         >-
      Neotoma contains data for a number of dataset types (see
      /dbtables/datasettypes.  This returns a subset of data types.
    in:                                  query
    required:                            false
    schema:
      type:                              string
      example:                           pollen
  familyNameQuery:
    name:                                    familyname
    description:                             Full name of the the researcher (may use the % wildcard)
    in:                                      query
    required:                                false
    schema:
      type:                                  string
  gpidPath:
    name:                                gpid
    in:                                  path
    description:                         Numeric ID for the geopolitical unit.
    required:                            true
    schema:
      type:                              integer
      format:                            int32
      minimum:                           0
  gpidQuery:
    name:                                gpid
    in:                                  query
    description:                         Numeric ID for the geopolitical unit.
    required:                            false
    schema:
      type:                              integer
      format:                            int32
      minimum:                           0
  gpnameQuery:
    name:                                gpname
    in:                                  query
    description:                         Name for a geopolitical unit.
    required:                            false
    schema:
      type:                              string
      example:                           Canada
  limitParam:
    name:                                    limit
    description:                             'The maximum number of records to be returned, default is 25.'
    schema:
      type:                                  integer
      format:                                int32
      default:                               25
      minimum:                               1
    in:                                      query
    required:                                false
  locQuery:
    name:                                    loc
    in:                                      query
    description:                             >
          The geographic region of interest for the site, as a GeoJSON string
          or valid Well Known Text (WKT).  Assumed projection of EPSG:4376
          unless otherwise defined.
    required:                                false
    schema:
      type:                                  string
      pattern: '^\{.*\}$'
  lowergpQuery:
    name:                                lower
    in:                                  query
    description:                         Should all lower ranked units below the target unit be returned?
    required:                            false
    schema:
      type:                              boolean
      default:                           false
  occurrenceidQuery:
    name:                                    occurrenceid
    description:                             Valid Neotoma occurrence identifier (integer), either singly or in a comma separated list.
    in:                                      query
    required:                                false
    schema:
      type:                                  integer
      format:                                int32
      minimum:                               0
  occurrenceidPath:
    name:                                    occurrenceid
    description:                             Valid Neotoma occurrence identifier (integer), either singly or in a comma separated list.
    in:                                      path
    required:                            true
    schema:
      type:                              integer
      format:                            int32
      minimum:                           0
      maximum: 10000000
  offsetParam:
    name:                                    offset
    description:                             >-
      The offset for returned records when a limit is present.  Default is
      0.
    in:                                      query
    required:                                false
    schema:
      type:                                  integer
      format:                                int32
      default:                               0
      minimum:                               0
  publicationidQuery:
    name:                                    publicationid
    description:                             >
      Unique publication identifier (from the Neotoma publication table).
    in:                                      query
    required:                                false
    schema:
      type:                                  integer
      format:                                int32
      minimum:                               0
  pubsearchQuery:
    name: search
    description: A fulltext search string.  Either a literal portion of the article name, or keywords.
    in: query
    required: false
    schema:
      type: string
  pubtypeQuery:
    name: pubtype
    description: The type of publication requested.
    required: false
    in: query
    schema:
      type: string
      enum: [Legacy, Journal Article, Book Chapter, Authored Book, Edited Book, Master's Thesis, Doctoral Dissertation, Authored Report, Edited Report, Other Authored, Other Edited, Website, Undergraduate thesis]
  pubyearQuery:
    name: year
    description: The year of publication, either as a single value or comma separated string.
    required: false
    in: query
    schema:
      type: integer
      format: int32
      minimum: 1500
      maximum: 2100
  rankQuery:
    name:                                rank
    in:                                  query
    description:                         'The unit rank.  Ranges from 1 (country) - 4 (e.g., parks).'
    required:                            false
    schema:
      type:                              integer
      minimum: 1
      maximum: 4
  siteidPath:
    name:                                    siteid
    description:                             Valid Neotoma site identifier (integer), either singly or in a comma separated list.
    in:                                      path
    required:                                true
    schema:
      type:                                  integer
      format:                                int32
      minimum:                               1
      maximum:  30000
  siteidQuery:
    name:                                    siteid
    description:                             Valid Neotoma site identifier (integer), either singly or in a comma separated list.
    in:                                      query
    required:                                false
    schema:
      type:                                  integer
      format:                                int32
      minimum:                               1
      maximum:  30000
  siteNameQuery:
    name:                                    sitename
    description:                             Name of the study site (may use the % wildcard)
    in:                                      query
    required:                                false
    schema:
      type:                                  string
      example:                               Stern Excavation Site
  tableQuery:
    name:                                    table
    description: Valid name for a Neotoma Table 
    in: query 
    required: false 
    schema:
      type: string
      example: sites
  taxonidPath:
    name:                                    taxonid
    description:                             >
      Unique taxonomic identifier (from the Neotoma taxon table).
    in:                                      path
    required:                                true
    schema:
      type:                                  integer
      format:                                int32
      minimum:                               1
      maximum: 50000
  taxonidQuery:
    in:                                      query
    name:                                    taxonid
    required:                                false
    description:                             Unique taxonomic identifier (from the Neotoma taxon table).
    schema:
      type:                                  integer
      minimum:                               1
      maximum: 50000
  taxonNameQuery:
    name:                                taxonname
    description:                         Taxon name or partial name.
    in:                                  query
    required:                            false
    schema:
      type:                              string
      example: "Canis"
  chronidPath:
    name:                                    chronid
    description:                             Unique chronology identifier.
    in:                                      path
    required:                                true
    schema:
      type:                                  integer
      format:                                int64
      minimum:                               0
  taxonnameQuery:
    in:                                      query
    name:                                    taxonname
    required:                                false
    description:                             Unique taxonomic name (from the Neotoma taxon table).
    schema:
      type:                                  string
